# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target '407tutorial1' do
  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'SwiftyJSON', '~> 2.3'
  pod 'AWSAPIGateway', '~> 2.3.2'
end

target '407tutorial1Tests' do

end

target '407tutorial1UITests' do

end

